### ISSUE TITLE
Key error when calling get_friends()

### ISSUE THREAD

**Issue by sylus58** [ro-py/ro.py#97]
**Describe the bug**

**To Reproduce**
When calling user.get_friends(), the following error is thrown:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\TkinterStuff\GUI.py", line 210, in buttonClick
    asyncio.get_event_loop().run_until_complete(getID(values_list))
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\TkinterStuff\GUI.py", line 183, in getID
    friends = await user.get_friends()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\roblox\bases\baseuser.py", line 112, in get_friends
    return [Friend(shared=self._shared, data=friend_data) for friend_data in friends_data]
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\roblox\bases\baseuser.py", line 112, in <listcomp>
    return [Friend(shared=self._shared, data=friend_data) for friend_data in friends_data]
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\roblox\friends.py", line 33, in __init__
    self.presence_type: int = data["presenceType"]
**KeyError: 'presenceType'**

**To Reproduce**
1. Call user.get_friends()
3. See error

**Expected behavior**
Returns a list of the users friends

**Comment by jmkd3v** [comment]
This is due to a Roblox API change - this is mitigated in the latest git version. For now, pull from git (`pip3 uininstall roblox; pip3 install git+https://github.com/ro-py/ro.py`) and this will be fixed upstream in the next month.

**Comment by sylus58** [comment]
That fixed it, thanks

**Comment by cfuendev** [comment]
is this bug still part of the latest pypi version? I got the exact same error just now.

I'm using `roblox==2.0.0`

```
Traceback (most recent call last):
  File "C:\Users\cfuen\Programming\Code\UEB\pwground\daki\test.py", line 97, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
           ^^^^^^^^^^^^^^^
  File "C:\Users\cfuen\Programming\Code\UEB\pwground\daki\test.py", line 93, in main
    friend_list = await user.get_friends()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cfuen\Programming\Code\UEB\pwground\.pwgr-env\Lib\site-packages\roblox\bases\baseuser.py", line 112, in get_friends
    return [Friend(shared=self._shared, data=friend_data) for friend_data in friends_data]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cfuen\Programming\Code\UEB\pwground\.pwgr-env\Lib\site-packages\roblox\bases\baseuser.py", line 112, in <listcomp>
    return [Friend(shared=self._shared, data=friend_data) for friend_data in friends_data]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cfuen\Programming\Code\UEB\pwground\.pwgr-env\Lib\site-packages\roblox\friends.py", line 33, in __init__
    self.presence_type: int = data["presenceType"]
                              ~~~~^^^^^^^^^^^^^^^^
KeyError: 'presenceType'
```
